platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: '2-sdk'

inputs:
  - name: pal-tracker
  - name: version

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |

    home_path=$(pwd)
    tmp_path=/tmp/pal-tracker
    
    mkdir -p $tmp_path
    cp pal-tracker/manifest-*.yml $tmp_path

    dotnet test ./pal-tracker/test/PalTrackerTests

    dotnet publish ./pal-tracker/src/PalTracker --configuration Release \
      --output $tmp_path/src/PalTracker/bin/Release/netcoreapp2.0/publish
    
    tar -C $tmp_path/ -cvzf ./build-output/pal-tracker-$(cat ./version/number).tgz .
    