---
resources:
- name: pal-tracker
  type: git
  source:
    uri: {{github-repository}}
    branch: master
    private_key: {{github-private-key}}

- name: pal-tracker-artifacts
  type: s3
  source:
    bucket: {{aws-bucket}}
    regexp: releases/pal-tracker-(.*).tgz
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: version
  type: semver
  source:
    bucket: {{aws-bucket}}
    key: pal-tracker/version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}

- name: review-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: review

- name: production-deployment
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: production

jobs:
- name: build
  plan:
  - get: pal-tracker
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build and test
    file: pal-tracker/ci/build.yml
  - put: pal-tracker-artifacts
    params:
      file: build-output/pal-tracker-*.tgz
  - put: version
    params:
      file: version/number

- name: deploy-review
  plan:
  - get: pal-tracker-artifacts
    params: {unpack: true}
    trigger: true
    passed: [build]
  - put: review-deployment
    params:
      manifest: pal-tracker-artifacts/manifest-review.yml
      path: pal-tracker-artifacts
      environment_variables:
        WELCOME_MESSAGE: Hello from the review environment

- name: deploy-production
  plan:
  - get: pal-tracker-artifacts
    params: {unpack: true}
    passed: [deploy-review]
  - put: production-deployment
    params:
      manifest: pal-tracker-artifacts/manifest-production.yml
      path: pal-tracker-artifacts
      environment_variables:
        WELCOME_MESSAGE: Hello from the production environment
